# Generated by Django 4.1.1 on 2022-09-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
