# Generated by Django 4.1.1 on 2022-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postText',
            field=models.TextField(),
        ),
    ]
