# Generated by Django 4.1 on 2022-09-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='pic',
            field=models.ImageField(default='default.png', upload_to='photos'),
        ),
    ]
