# Generated by Django 4.1 on 2022-09-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useraccount_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='pic',
        ),
    ]
